---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:

    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
    
    - name: Do an apt full-upgrade
      ansible.builtin.apt:
        upgrade: full

    - name: Install initial apt dependencies
      ansible.builtin.apt:
        name: "{{ init_apt_packages }}"
        state: present
    
    - name: Install pip initial dependencies
      ansible.builtin.pip:
        name: "{{ init_pip_packages }}"
        state: present
    
    - name: Get hashicorp repo gpg key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Install hashicorp repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
        state: present
        update_cache: yes  

    - name: Uninstall previous docker versions
      ansible.builtin.apt:
        name: "{{ rm_apt_packages }}"
        state: absent
    
    - name: Get docker repo gpg key
      ansible.builtin.shell:
        cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Install docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal main
        state: present
        update_cache: yes
    
    - name: Install awscli v2
      ansible.builtin.shell:
        cmd: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install

    - name: Get microsoft repo gpg key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add azurecli repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main
        state: present
        update_cache: yes

    - name: Get kubernetes repo gpg key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add kubernetes repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        update_cache: yes


        